:PROPERTIES:
:ID:       e6078fc8-4b12-44ad-b008-20f0b7311069
:END:
#+LANGUAGE: en
#+EXPORT_FILE_NAME: ./controlling_my_music.md
#+SUBTITLE: Controlling my music player with clk, from a simple alias to a bash command

#+CALL: ../../lp.org:check-result()

#+name: init
#+BEGIN_SRC bash :results none :exports none :session e6078fc8-4b12-44ad-b008-20f0b7311069
  . ./sandboxing.sh
#+END_SRC

* wrapping the music player
  :PROPERTIES:
  :CUSTOM_ID: wrapping-the-music-player
  :END:

Let's imagine you want to use clk to control your musicplayer. Chances are there
already exists some command line tool to do so and that you want to wrap it into
clk to take advantages of aliases, parameters and flows.

On that case, you most likely will want to create a simple alias on top of exec.

For the sake of this example, let's use this fake music control program and call
it 'mpc'.

#+NAME: fake_control_program
#+BEGIN_SRC bash :results none :exports code
  if test "$1" = history
  then
      printf '%s\n' Kind-of-Blue Bitches-Brew Kind-of-Blue Blue-Train Bitches-Brew
      exit 0
  fi
  echo "Running mpc with: $*"
#+END_SRC

#+NAME: install_fake_music_program
#+BEGIN_SRC bash :results none :exports none :session e6078fc8-4b12-44ad-b008-20f0b7311069 :noweb yes
  mkdir -p "${TMP}/bin"
  export PATH="${TMP}/bin:${PATH}"
  cat <<"EOF" > "${TMP}/bin/mpc"
  #!/usr/bin/env bash
  <<fake_control_program>>
  EOF
  chmod +x "${TMP}/bin/mpc"
#+END_SRC

Then, to use this program as a clk command, we could simply create an alias
like this.

#+NAME: create
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
  clk alias set music.play exec -- mpc play --random --use-speakers --replaygain
#+END_SRC

#+RESULTS[b647c2a71f82abeed6340d9486c5c23e9c81bf75]: create
: New global alias for music.play: exec mpc play --random --use-speakers --replaygain


Then, we can simple call this command.

#+NAME: use_play
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
  clk music play MyAlbum
#+END_SRC

#+RESULTS[528d993ebba0114a75f77f47b1b7e61de533e885]: use_play
: Running mpc with: play --random --use-speakers --replaygain MyAlbum

* parameters and completion
  :PROPERTIES:
  :CUSTOM_ID: parameters-and-completion
  :END:

We get the benefit of parameters, flow etc.

#+NAME: use_parameters
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music play --repeat --set-parameter global
clk music play MyAlbum
#+END_SRC

#+RESULTS[878efeb6fda1602dbdb5296cb1a67cfa8adb7c78]: use_parameters
: New global parameters for music.play: --repeat
: Running mpc with: play --random --use-speakers --replaygain --repeat MyAlbum

Of course, ~--set-parameter~ provides completion for the profile name. Here,
only ~global~ is available since we don't have a project.

#+NAME: sequence-to-complete
#+BEGIN_SRC bash :results none :exports none
  music play --set-parameter g
#+END_SRC

#+NAME: ask-for-completion
#+BEGIN_SRC bash :results none :exports code :noweb yes
  clk <<sequence-to-complete>><TAB>
#+END_SRC

#+NAME: try-completion
#+BEGIN_SRC bash :results verbatim :exports results :noweb yes :cache yes :session e6078fc8-4b12-44ad-b008-20f0b7311069
  clk completion try --last -- <<sequence-to-complete>>
#+END_SRC

#+RESULTS[7ac141da6b6844471cc5dec64f6979ba425df20e]: try-completion
: global

* when one command is not enough
  :PROPERTIES:
  :CUSTOM_ID: when-one-command-is-not-enough
  :END:

Chances are that, after some time, we realize that this command should be a
little more complicated than wrapping a single executable. For instance, we
could want to start some music server, then play some music.

We could do this with a more complicated alias.

#+NAME: more_complicated_alias
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
  clk alias set music.play exec mpc start-server , exec -- mpc play --random --use-speakers --replaygain
  clk music play MyAlbum
#+END_SRC

#+RESULTS[f006cf9ec91386ec657cccf56629f0a2b23f94a7]: more_complicated_alias
: Removing global alias of music.play: exec mpc play --random --use-speakers --replaygain
: New global alias for music.play: exec mpc start-server , exec mpc play --random --use-speakers --replaygain
: Running mpc with: start-server
: Running mpc with: play --random --use-speakers --replaygain --repeat MyAlbum

As aliases grow, you may need to take a look at what it does to avoid getting
lost.

You can call the alias command to do so.

#+NAME: show-alias
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk alias show music.play
#+END_SRC

#+RESULTS[ec752b2d64d3875b3cd1344259fc4b3c49233e01]: show-alias
: music.play exec mpc start-server, exec mpc play --random --use-speakers --replaygain

Note that showing the help of the command also gives that information.

#+NAME: help-alias
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music play --help|head -10
#+END_SRC

#+RESULTS[da13213a5b95d29790482b257f938028808294d4]: help-alias
: Usage: clk music play [OPTIONS] [COMMAND]...
:
:   Alias for: exec mpc start-server , exec mpc play --random --use-speakers --replaygain
:
:   The current parameters set for this command are: --repeat
:
:   Edit this alias by running `clk alias edit music.play`
:   Or adjust this command `clk alias set music.play exec mpc start-server , exec mpc play --random --use-speakers
:   --replaygain`


Let's take that first advice and add the step that waits for the server.

#+NAME: edit-alias
#+BEGIN_SRC bash :results none :exports code :session e6078fc8-4b12-44ad-b008-20f0b7311069
clk alias edit music.play
#+END_SRC

Your editor opens on the commands, one per line. Leave this in it.

#+NAME: editor-content
#+BEGIN_SRC bash :results none :exports code
exec mpc start-server
exec mpc wait-for-server
exec mpc play --random --use-speakers --replaygain
#+END_SRC

#+NAME: prepare-editor
#+BEGIN_SRC bash :results none :exports none :session e6078fc8-4b12-44ad-b008-20f0b7311069 :noweb yes
editor_writes <<'EOF'
<<editor-content>>
EOF
#+END_SRC

#+NAME: run-edited-alias
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music play MyAlbum
#+END_SRC

#+RESULTS[]: run-edited-alias
: Running mpc with: start-server
: Running mpc with: wait-for-server
: Running mpc with: play --random --use-speakers --replaygain --repeat MyAlbum

* falling back to a real command
  :PROPERTIES:
  :CUSTOM_ID: falling-back-to-a-real-command
  :END:

Even doing so, you may at some point want more control about what you are doing,
like really waiting for the music server rather than asking it to, and you will
have to fall back in a real command. Replacing this alias with a shell command is
straightforward:

#+NAME: bootstrap
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk command create bash --replace-alias music.play
#+END_SRC

#+RESULTS[5faaca627fd5783bd0facfee4ad8845a696ab9c9]: bootstrap
: Erasing music.play alias from global settings

This command tries hard to have the same behavior as its original alias.

#+NAME: try_command
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music play MyAlbum
#+END_SRC

#+RESULTS[]: try_command
: Running mpc with: start-server
: Running mpc with: wait-for-server
: Running mpc with: play --random --use-speakers --replaygain --repeat MyAlbum

Now, we can change its content to do whatever complicated flow we like.

You can simply run ~clk command edit music.play~ and it will be open in the
editor mentioned in the ~EDITOR~ environment variable.

If instead, you want to get the path of the command to open it yourself, you can simply ask for it.

#+NAME: which
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk command which music.play
#+END_SRC

#+RESULTS[322038d7fe4653f51bd57db2b6a3b0747fffe040]: which
: ./clk-root/bin/music.play

Note that it is also shown in the help of the command.

#+NAME: help
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music play --help|head -10
#+END_SRC

#+RESULTS[da13213a5b95d29790482b257f938028808294d4]: help
#+begin_example
Usage: clk music play [OPTIONS] [ARGS]...

  Description Converted from the alias music.play

  The current parameters set for this command are: --repeat

  Edit this external command by running `clk command edit music.play`
  Or edit ./clk-root/bin/music.play directly.

Positional arguments:
#+end_example

* saying what the command takes
  :PROPERTIES:
  :CUSTOM_ID: saying-what-the-command-takes
  :END:

That command passes the whole line to mpc. Say what it really takes.

#+NAME: album-usage
#+BEGIN_SRC bash :results none :exports code
A:album:str:The album to play
F:--repeat:Keep playing it
#+END_SRC

#+NAME: album-body
#+BEGIN_SRC bash :results none :exports code
args=()
if clk_true repeat
then
    args+=(--repeat)
fi
clk exec mpc start-server
clk exec mpc wait-for-server
clk exec mpc play --random --use-speakers --replaygain "${args[@]}" "$(clk_value album)"
#+END_SRC

#+NAME: write-album-command
#+BEGIN_SRC bash :results none :exports none :session e6078fc8-4b12-44ad-b008-20f0b7311069 :noweb yes
cat<<"EOH" > "$(clk command which music.play)"
#!/usr/bin/env bash
  set -eu

source "_clk.sh"

clk_usage () {
    cat<<EOF
$0

Play an album
--
<<album-usage>>
EOF
}

clk_help_handler "$@"

<<album-body>>

EOH
#+END_SRC

#+NAME: play-an-album
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music play Kind-of-Blue
#+END_SRC

#+RESULTS[]: play-an-album
: Running mpc with: start-server
: Running mpc with: wait-for-server
: Running mpc with: play --random --use-speakers --replaygain --repeat Kind-of-Blue

* playing it loud
  :PROPERTIES:
  :CUSTOM_ID: playing-it-loud
  :END:

Loud as well is two steps, so an alias again.

#+NAME: music-loud
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk alias set music.loud exec mpc volume 100 , music play
clk music loud Kind-of-Blue
#+END_SRC

#+RESULTS[]: music-loud
: New global alias for music.loud: exec mpc volume 100 , music play
: Running mpc with: volume 100
: Running mpc with: start-server
: Running mpc with: wait-for-server
: Running mpc with: play --random --use-speakers --replaygain --repeat Kind-of-Blue

Tidying up, I unset ~music.pause~, which I renamed long ago, and clk answers
with the aliases I do have.

#+NAME: unset-gone-alias
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk alias unset music.pause 2>&1
#+END_SRC

#+RESULTS[]: unset-gone-alias
: Usage: clk alias unset [OPTIONS] [ALIASES]...
: error: Invalid value for '[ALIASES]...': invalid choice: music.pause. (choose from music.loud)

That one grows in its turn, and the album follows it into the command.

#+NAME: convert-music-loud
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk command create bash --replace-alias music.loud
clk music loud Bitches-Brew
#+END_SRC

#+RESULTS[]: convert-music-loud
: Erasing music.loud alias from global settings
: Running mpc with: volume 100
: Running mpc with: start-server
: Running mpc with: wait-for-server
: Running mpc with: play --random --use-speakers --replaygain --repeat Bitches-Brew

* the albums I played lately
  :PROPERTIES:
  :CUSTOM_ID: the-albums-i-played-lately
  :END:

~mpc history~ gives the albums in the order they played, the same ones over and
over. I want to see each of them once, in that order, and ~clk_drop_duplicate~
does exactly that. It comes with the other helpers of ~_clk.sh~, the ones your
bash commands source.

#+NAME: create-recent
#+BEGIN_SRC bash :results verbatim :exports code :session e6078fc8-4b12-44ad-b008-20f0b7311069
clk command create bash music.recent --description "The albums I played lately" \
    --body 'clk exec mpc history | clk_drop_duplicate'
#+END_SRC

#+NAME: run-recent
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music recent
#+END_SRC

#+RESULTS[]: run-recent
: Kind-of-Blue
: Bitches-Brew
: Blue-Train

* coming back to it after a while
  :PROPERTIES:
  :CUSTOM_ID: coming-back-to-it-after-a-while
  :END:

Time passes, I upgrade clk. My settings were written in json back then, and I
had dropped a script of mine in the bin, ~music.shuffle.py~, that I called with
~clk music shuffle@py~.

#+NAME: old-config
#+BEGIN_SRC bash :results none :exports none :session e6078fc8-4b12-44ad-b008-20f0b7311069
cat<<'EOF' > "${CLKCONFIGDIR}/clk.json"
{
  "parameters": {
    "music.play": ["--repeat"],
    "music.shuffle@py": ["--seed", "42"]
  }
}
EOF
rm "${CLKCONFIGDIR}/clk.json5"
echo 8 > "${CLKCONFIGDIR}/version.txt"
cat<<'EOF' > "${CLKCONFIGDIR}/bin/music.shuffle.py"
#!/usr/bin/env python3
print("shuffling")
EOF
chmod +x "${CLKCONFIGDIR}/bin/music.shuffle.py"
mkdir -p "${CLKCONFIGDIR}/python"
cat<<'EOF' > "${CLKCONFIGDIR}/python/mixer.py"
from clk.config import DynamicConfigBase


class Mixer(DynamicConfigBase):
    pass
EOF
#+END_SRC

The first clk I run writes the settings in json5. The @ is gone, so it renames
my script too, and it tells me what it cannot fix.

#+NAME: migrate
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music play Kind-of-Blue 2>&1
#+END_SRC

#+RESULTS[]: migrate
: warning: Profile in ./clk-root is obsolete. It has the version 8 and current version is 9. Migration started.
: warning: Renaming music.shuffle.py into music.shuffle, so that it answers to music shuffle
: warning: mixer.py uses DynamicConfigBase, which is gone: expose_class does the same
: Running mpc with: start-server
: Running mpc with: wait-for-server
: Running mpc with: play --random --use-speakers --replaygain --repeat Kind-of-Blue

My parameters followed the new name.

#+NAME: shuffle-after
#+BEGIN_SRC bash :results verbatim :exports both :session e6078fc8-4b12-44ad-b008-20f0b7311069 :cache yes
clk music shuffle
clk parameter show music.shuffle
#+END_SRC

#+RESULTS[]: shuffle-after
: warning: The command 'music.shuffle' has no documentation
: shuffling
: music.shuffle --seed 42

#+BEGIN_SRC bash :exports none :tangle ../../tests/use_cases/controlling_my_music.sh :noweb yes :shebang "#!/usr/bin/env bash"
  set -eu
  <<init>>
  <<install_fake_music_program>>
  check-result(create)
  check-result(use_play)
  check-result(use_parameters)
  check-result(try-completion)
  check-result(more_complicated_alias)
  check-result(show-alias)
  check-result(help-alias)

  <<prepare-editor>>

  <<edit-alias>>

  check-result(run-edited-alias)
  check-result(bootstrap)
  check-result(try_command)
  check-result(which)
  check-result(help)

  <<write-album-command>>

  check-result(play-an-album)

  check-result(music-loud)

  check-result(unset-gone-alias)

  check-result(convert-music-loud)

  <<create-recent>>

  check-result(run-recent)

  <<old-config>>

  check-result(migrate)

  check-result(shuffle-after)
#+END_SRC
