:PROPERTIES:
:ID:       f47428c2-56ea-4d91-97d9-4f2ff63ef052
:END:
#+language: en
#+options: toc:t
#+EXPORT_FILE_NAME: ./creating_extensions.md
#+SUBTITLE: Creating and sharing extensions (folders of commands and configuration)

#+CALL: ../../lp.org:check-result()

#+name: init
#+BEGIN_SRC bash :results none :exports none :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
  . ./sandboxing.sh
#+END_SRC
Extensions are folders that contain clk configurations and commands. You can create and share those with your colleagues.

For instance, let's suppose you need to bootstrap a development environment to
work with k8s, you would need to create commands to:
- install the needed binaries dependencies,
- run the cluster,
- start some controllers of your choice,
- run the development environment that would update the cluster automatically,
- setup some credentials into the dev cluster.

* creating our own extension
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:36]
  :ID:       ce7e4602-baad-4ce6-8b44-33d5480a264b
  :CUSTOM_ID: 578ef2c9-a4d4-448a-9d56-be4afe4ac64a
  :END:

The real life extension can be found in [[https://github.com/clk-project/clk_extension_k8s][here]]. In this document, we will mock its
behavior. There should be something like.

#+NAME: k8s
#+BEGIN_SRC python :results none :exports code
@k8s.command()
def install_dependencies():
    """Install the required binary dependencies for k8s development."""
    print("installing dependencies")

@k8s.command(flowdepends=["k8s.install-dependencies"])
def run_cluster():
    """Start the Kubernetes cluster."""
    print("starting k8s cluster")

@k8s.command(flowdepends=["k8s.run-cluster"])
def start_controllers():
    """Start the necessary controllers for the k8s environment."""
    print("starting controllers")

@k8s.command(flowdepends=["k8s.start-controllers"])
def setup_credentials():
    """Placeholder to setup whatever credentials you need."""
    print("noop, this must be overloaded by a project command")

@k8s.command(flowdepends=["k8s.setup-credentials"])
def run_dev_env():
    """Run the development environment with automatic cluster updates."""
    print("running development environment")

#+END_SRC

To share them, you would first need to create the extension named k8s.

#+NAME: create_extension
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension create k8s
#+END_SRC

Them, create the k8s command inside the extension.

#+NAME: create_k8s
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052 :noweb yes
clk command create --extension k8s python k8s --group --description "Deal with k8s stuff" --body '
<<k8s>>
'
#+END_SRC

Try it with

#+NAME: try-it
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk k8s run-dev-env --flow
#+END_SRC

#+RESULTS[dca9e20533f99e1b8bd8894585c93baaa2938506]: try-it
: installing dependencies
: starting k8s cluster
: starting controllers
: noop, this must be overloaded by a project command
: running development environment

* enable/disable it
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:36]
  :CUSTOM_ID: 72f61beb-cd79-4fdd-86a2-2c56ef08292c
  :END:

Note that once it is there, the extension is automatically enabled.

Now, if you decide that you don't want to be bothered with that extension anymore, you can disable it.

#+NAME: disable
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension disable k8s
clk k8s run-dev-env --flow
#+END_SRC

#+RESULTS[caa531b03ee6b31d35eed3a0dc93b254d4545bbc]: disable
: warning: Failed to get the command k8s: Command k8s not found
: Usage: clk [OPTIONS] [COMMAND] [ARGS]...
: error: No such command 'k8s'.

While it is disabled, you can still call it for one command line, without
changing your mind about it.

#+NAME: enable-for-one-run
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk --extension k8s k8s run-dev-env --flow
#+END_SRC

#+RESULTS[a7fd0ca4345516df4f365241e2f33c936d25c760]: enable-for-one-run
: installing dependencies
: starting k8s cluster
: starting controllers
: noop, this must be overloaded by a project command
: running development environment

You can enable it again with.

#+NAME: enable
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension enable k8s
clk k8s run-dev-env --flow
#+END_SRC

#+RESULTS[4e819e7f946a0c3fb4c8bc4ba83d438fa796c0c5]: enable
: installing dependencies
: starting k8s cluster
: starting controllers
: noop, this must be overloaded by a project command
: running development environment

The other way round works too, to leave it out of a single command line.

#+NAME: disable-for-one-run
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk --without-extension k8s k8s run-dev-env --flow
#+END_SRC

#+RESULTS[4013dc3f99e58fd5bc22301405cb090b961a30ca]: disable-for-one-run
: warning: Failed to get the command k8s: Command k8s not found
: Usage: clk [OPTIONS] [COMMAND] [ARGS]...
: error: No such command 'k8s'.

* generic programming
  :PROPERTIES:
  :CREATED:  [2026-08-18 17:52]
  :CUSTOM_ID: 7e7ae624-ce8a-4470-8bb0-7a44d8c2caea
  :END:

  You have noticed that we created a command named setup-credential. In general,
  the author of the extension does not know in advance the kind of credentials
  that must be injected in the stack, but the extension can still provide a
  "placeholder" command that does nothing and is replaced by a more specific one in the project.

  For instance, let's create a local bash script to write some credentials. It
  needs a project to live in.

  #+NAME: create_credentials_project
  #+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
  mkdir myproject && cd myproject && mkdir .clk
  #+END_SRC

  In there, the script only has to care about the credentials.

  #+NAME: setup_credentials_body
  #+BEGIN_SRC bash :results none :exports code
  echo "injecting the credentials of my project"
  #+END_SRC

  Because it is defined in the project, it takes precedence over the placeholder
  of the extension. The flow dependencies were described by the placeholder
  though, and our script depends on nothing, so we ask to inherit the ones of
  the command we hide with ~[overridden]~.

  #+NAME: create_local_credentials
  #+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052 :noweb yes
  clk command create bash k8s.setup-credentials --flowdeps '[overridden]' --description "Setup the credentials of this project" --body '
  <<setup_credentials_body>>
  '
  #+END_SRC

  That way, the step does something useful and the flow still runs whole.

  #+NAME: run-flow-in-project
  #+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
  clk k8s run-dev-env --flow
  #+END_SRC

  #+RESULTS[dca9e20533f99e1b8bd8894585c93baaa2938506]: run-flow-in-project
  : installing dependencies
  : starting k8s cluster
  : starting controllers
  : injecting the credentials of my project
  : running development environment

  It is an opt-in, so that you never inherit a flow you did not ask for. Also,
  ~[overridden]~ keeps its position, hence you may run something before or after
  the inherited dependencies.

  Leaving the project brings the placeholder back, so that the flow keeps working
  everywhere.

  #+NAME: leave_credentials_project
  #+BEGIN_SRC bash :results none :exports none :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
  cd ..
  #+END_SRC

  That way, the extension provides the workflow and each project provides only
  the parts that are specific to it. An alias would have done as well, would you
  rather describe the credentials in terms of other clk commands.

* publish it
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:37]
  :CUSTOM_ID: 21d2895b-db01-4a09-b2a2-18e34e2830b6
  :END:

In case you lost that extension folder and want to find it again, simply run.

#+NAME: find-it
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension where-is global/k8s
#+END_SRC

#+RESULTS[5ee58c93da49807a24b9fab6e6bb97026578103e]: find-it
: ./clk-root/extensions/k8s

That folder is only code, so git can carry it. A fresh repository wants to know
who you are, and then it is a push like any other.

#+NAME: publish-k8s
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
git init --bare "${TMP}/k8s.git"
cd "$(clk extension where-is global/k8s)"
git init
echo "__pycache__/" > .gitignore
git add .
git -c user.email=you@example.com -c user.name=You commit -m "the k8s extension"
git remote add origin "${TMP}/k8s.git"
git push origin HEAD
cd "${TMP}"
#+END_SRC

Now lose it, the way your colleagues have never had it.

#+NAME: lose-k8s
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove k8s
clk k8s run-dev-env --flow 2>&1 | tail -1
#+END_SRC

#+RESULTS[82ee81e8b49da3068773d6ce6957dfd75aedaea6]: lose-k8s
: error: No such command 'k8s'.

~clk extension install~ takes that url. It would guess the name from the url, so
say the one you want.

#+NAME: install-k8s
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension install "${TMP}/k8s.git" k8s
#+END_SRC

And the whole flow answers again.

#+NAME: k8s-is-back
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk k8s run-dev-env --flow
#+END_SRC

#+RESULTS[dca9e20533f99e1b8bd8894585c93baaa2938506]: k8s-is-back
: installing dependencies
: starting k8s cluster
: starting controllers
: noop, this must be overloaded by a project command
: running development environment

Should someone hand you another repository under that same name, clk would rather
say no than pull a stranger over what you have.

#+NAME: another-k8s
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
git init --bare "${TMP}/someone-else.git"
#+END_SRC

#+NAME: refuse-another-k8s
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension install "${TMP}/someone-else.git" k8s 2>&1 | sed "s|$(pwd)|.|" | tail -1
#+END_SRC

#+RESULTS[87ce96f50b2fff9e34a86e9ba955db91a80c5b0f]: refuse-another-k8s
: error: Extension k8s already exists and is not using the same URL: ./k8s.git

Meanwhile a colleague of yours writes the command that stops the cluster, and
pushes it to that same repository.

#+NAME: colleague-adds
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
git clone "${TMP}/k8s.git" "${TMP}/their-k8s"
cd "${TMP}/their-k8s"
mkdir -p bin
cat <<'EOF' > bin/stop-cluster
#!/usr/bin/env bash
echo "stopping k8s cluster"
EOF
chmod +x bin/stop-cluster
git add .
git -c user.email=them@example.com -c user.name=Them commit -m "stop the cluster too"
git push origin HEAD
cd "${TMP}"
#+END_SRC

You do not have it yet.

#+NAME: no-stop-cluster
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk stop-cluster 2>&1 | tail -1
#+END_SRC

#+RESULTS[9ccb0ccdea569e96403d50df2ebbc3f4a2793963]: no-stop-cluster
: error: No such command 'stop-cluster'.

~clk extension update~ pulls the clone, and what they wrote is yours.

#+NAME: update-k8s
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension update k8s
#+END_SRC

#+NAME: stop-cluster
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk stop-cluster 2>/dev/null
#+END_SRC

#+RESULTS[d9710497821a7fe46a260e8748d7fd7f53b4ea11]: stop-cluster
: stopping k8s cluster

* get an extension
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:37]
  :ID:       2907a837-a58d-479b-8d19-7cba1c9a408f
  :CUSTOM_ID: b7bcef53-dd68-4660-9c5c-d9aa029d1a72
  :END:

Let's try to install another extension for the sake of learning. Let's try to
install the one available in https://github.com/clk-project/clk_extension_hello
. It does nothing useful. It simply says hello in a funny way.

There are three ways to provide the url to the extension:
1. use the full url to the git remote,
2. if it is hosted in github, and its repository name is something like
   ~clk_extension_NAME~, then you can simply pass ~<GITHUB_OWNER>/<NAME>~. This
   will be automatically changed into ~https://github.com/<GITHUB_OWNER>/clk_extension_<NAME>~.
3. if it is an official extension provided by clk (meaning hosted at https://github.com/orgs/clk-project/repositories with the
   prefix ~clk_extension_~), then the name will suffice.


Let's try the three methods.

#+NAME: install-extension
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension install https://github.com/clk-project/clk_extension_hello > /dev/null 2>&1
clk hello
#+END_SRC

#+RESULTS[ddc8b5f07fbf3c07198b62e1c6dd77537bdce685]: install-extension
#+begin_example
_____
| hello |
  =====
       \
        \
         \
          \
                                / \\  //\\
                 |\\___/|      /   \\//  \\\\
                 /0  0  \\__  /    //  | \\ \\
                /     /  \\/_/    //   |  \\  \\
                \@_^_\@'/   \\/_   //    |   \\   \\
                //_^_/     \\/_ //     |    \\    \\
             ( //) |        \\///      |     \\     \\
           ( / /) _|_ /   )  //       |      \\     _\\
         ( // /) '/,_ _ _/  ( ; -.    |    _ _\\.-~        .-~~~^-.
       (( / / )) ,-{        _      `-.|.-~-.           .~         `.
      (( // / ))  '/\\      /                 ~-. _ .-~      .-~^-.  \\
      (( /// ))      `.   {            }                   /      \\  \\
       (( / ))     .----~-.\\        \\-'                 .~         \\  `. \\^-.
                  ///.----..>        \\             _ -~             `.  ^-`  ^-_
                    ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                       /.-~
#+end_example

An extension you did not write yourself leaves you wondering what is in it.
~clk extension describe~ answers that.

#+NAME: describe-hello
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension describe global/hello
#+END_SRC

#+RESULTS[79ac3c6a1c7b2351a3d7e590077e83fe0fc13fe8]: describe-hello
: The extension global/hello is located at ./clk-root/extensions/hello . Let's try to see what it has to offer.
: ##########
: I found some alias:
:   hello: say hello
: I found some parameter:
:   hello: --who dragon
: I found some commands:
:   say

Remove the extension with

#+NAME: remove-extension
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove hello
clk hello
#+END_SRC

#+RESULTS[16bb914fcc2d2d14fd1d6f6aa8abf780c09ddedd]: remove-extension
: warning: Failed to get the command hello: Command hello not found
: Usage: clk [OPTIONS] [COMMAND] [ARGS]...
: error: No such command 'hello'.
: error:
: error: Did you mean one of these?
: error:     help
: error:     log

Because it is hosted on github, this should do as well to install it.

#+NAME: install-extension-github
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension install clk-project/hello > /dev/null 2>&1
clk hello
#+END_SRC

#+RESULTS[49c1c62970af8db344f9ad2e27ecb87082431174]: install-extension-github
#+begin_example
_____
| hello |
  =====
       \
        \
         \
          \
                                / \\  //\\
                 |\\___/|      /   \\//  \\\\
                 /0  0  \\__  /    //  | \\ \\
                /     /  \\/_/    //   |  \\  \\
                \@_^_\@'/   \\/_   //    |   \\   \\
                //_^_/     \\/_ //     |    \\    \\
             ( //) |        \\///      |     \\     \\
           ( / /) _|_ /   )  //       |      \\     _\\
         ( // /) '/,_ _ _/  ( ; -.    |    _ _\\.-~        .-~~~^-.
       (( / / )) ,-{        _      `-.|.-~-.           .~         `.
      (( // / ))  '/\\      /                 ~-. _ .-~      .-~^-.  \\
      (( /// ))      `.   {            }                   /      \\  \\
       (( / ))     .----~-.\\        \\-'                 .~         \\  `. \\^-.
                  ///.----..>        \\             _ -~             `.  ^-`  ^-_
                    ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                       /.-~
#+end_example

And because this is also a clk provided extension, the name is enough.

#+NAME: install-extension-name
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove hello
clk extension install hello > /dev/null 2>&1
clk hello
#+END_SRC

#+RESULTS[57260c733fd9dbb7ef455f4c6a567e0fab79bc82]: install-extension-name
#+begin_example
_____
| hello |
  =====
       \
        \
         \
          \
                                / \\  //\\
                 |\\___/|      /   \\//  \\\\
                 /0  0  \\__  /    //  | \\ \\
                /     /  \\/_/    //   |  \\  \\
                \@_^_\@'/   \\/_   //    |   \\   \\
                //_^_/     \\/_ //     |    \\    \\
             ( //) |        \\///      |     \\     \\
           ( / /) _|_ /   )  //       |      \\     _\\
         ( // /) '/,_ _ _/  ( ; -.    |    _ _\\.-~        .-~~~^-.
       (( / / )) ,-{        _      `-.|.-~-.           .~         `.
      (( // / ))  '/\\      /                 ~-. _ .-~      .-~^-.  \\
      (( /// ))      `.   {            }                   /      \\  \\
       (( / ))     .----~-.\\        \\-'                 .~         \\  `. \\^-.
                  ///.----..>        \\             _ -~             `.  ^-`  ^-_
                    ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                       /.-~
#+end_example

* leaning on the helpers of clk.lib
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:38]
  :ID:       a1b2c3d4-5678-90ab-cdef-1234567890ab
  :CUSTOM_ID: 795e915b-29f5-4fbc-a8d9-480a094d3e37
  :END:

** tempdir
   :PROPERTIES:
   :CUSTOM_ID: 60d4bff1-366d-45cb-b0ce-3bb7468734aa
   :END:

~tempdir()~ creates a temporary directory and returns its path. It is useful
when you need to extract archives and move files around.

Let's mock a typical use case: installing a tool by extracting an archive and
moving the binary to a destination. This pattern is used in the [[https://github.com/clk-project/clk_extension_k8s][k8s extension]]
to install helm, tilt, etc.

#+NAME: create_tempdir_extension
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension create tempdir-demo
#+END_SRC

#+NAME: create_tempdir_command
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk command create --extension tempdir-demo python tempdir-demo --group --description "Demonstrate tempdir usage" --body '
from pathlib import Path
from clk.lib import tempdir, makedirs, move

@tempdir_demo.command()
def install_mock_tool():
    """Mock installing a tool by extracting an archive to a temp dir."""
    install_dir = Path(".")
    with tempdir() as d:
        # Simulate extracting an archive (in real code: extract(url, d))
        extracted_dir = Path(d) / "tool-1.0.0"
        makedirs(extracted_dir)
        tool_binary = extracted_dir / "tool"
        tool_binary.write_text("#!/bin/sh\necho tool v1.0.0")

        # Move the binary to install location
        dest = install_dir / "mock-tool"
        move(tool_binary, dest)
        print(f"Installed: {dest.read_text()}")
    # temp dir is automatically cleaned up
    # clean up the installed file for the demo
    (install_dir / "mock-tool").unlink()
'
#+END_SRC

#+NAME: run-tempdir-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk tempdir-demo install-mock-tool
#+END_SRC

#+RESULTS[f49599b43da3200cf9e53511db4e2aa74ea4fcc3]: run-tempdir-demo
: Installed: #!/bin/sh
: echo tool v1.0.0

** temporary_file
   :PROPERTIES:
   :CUSTOM_ID: d18237dd-7e05-4225-b9de-bf63f09b6d99
   :END:

~temporary_file()~ creates a temporary file. You can optionally pass ~content~
to write initial content. The file is automatically removed when leaving the
context.

This is useful when you need to pass configuration to a command that reads from
a file. The [[https://github.com/clk-project/clk_extension_k8s][k8s extension]] uses this pattern to pass YAML configuration to
kubectl.

#+NAME: create_tempfile_command
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk command create --extension tempdir-demo python apply-mock-config --description "Demonstrate temporary_file usage" --body '
from clk.lib import temporary_file, check_output

@command()
def apply_mock_config():
    """Mock applying a k8s config using a temporary file."""
    config = """apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  key: value
"""
    with temporary_file(content=config) as f:
        # In real code: call(["kubectl", "apply", "-f", f.name])
        # Here we just cat the file to show it works
        result = check_output(["cat", f.name])
        print("Applied config:")
        print(result.strip())
    # temp file is automatically cleaned up
'
#+END_SRC

#+NAME: run-tempfile-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk apply-mock-config
#+END_SRC

#+RESULTS[d60f9eef68024528f834ad05173540d29f525def]: run-tempfile-demo
: Applied config:
: apiVersion: v1
: kind: ConfigMap
: metadata:
:   name: my-config
: data:
:   key: value

#+NAME: cleanup-tempdir-demo
#+BEGIN_SRC bash :results none :exports none :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove tempdir-demo
#+END_SRC

** check_output
   :PROPERTIES:
   :CREATED:  [2026-09-11 12:00]
   :CUSTOM_ID: 5fab2cd5-3e10-4c2c-ac79-038abeec8a41
   :END:

You know ~check_output~ from the standard library. The one in ~clk.lib~ wraps it
with what a command needs.

Let's create a command asking a program about the cluster we name. That program
complains on its error output, and gives up on every cluster but ~main~.

#+NAME: create_failing_extension
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension create cluster-demo
#+END_SRC

#+NAME: create_failing_command
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk command create --extension cluster-demo python check-cluster --description "Ask a program about a cluster" --body '
from clk.lib import check_output

@command()
@argument("cluster", help="The cluster to ask about")
@flag("--quiet", help="Do not pass on what the program says on its error output")
def check_cluster(cluster, quiet):
    """Ask a program about a cluster."""
    print(check_output(["bash", "-c", "echo trouble reaching $1 >&2 ; test $1 = main || exit 4 ; echo ok", "--", cluster], nostderr=quiet).strip())
'
#+END_SRC

Ask it about ~main~.

#+NAME: run-complaining-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk check-cluster main 2>&1
#+END_SRC

#+RESULTS[c0ef6b5f405a45f312e21752abedefa5ab7e208b]: run-complaining-demo
: trouble reaching main
: ok

And if you want to get rid of the warning.

#+NAME: run-quiet-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk check-cluster --quiet main 2>&1
#+END_SRC

#+RESULTS[9729072330be063ffdc004dd63dd21a8f0aeb3d4]: run-quiet-demo
: ok

Now ask about a cluster the program cannot reach.

#+NAME: run-failing-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk check-cluster other 2>&1
#+END_SRC

#+RESULTS[49b6057dd637b77fa5716a9a2bc288f5525c3ab4]: run-failing-demo
: trouble reaching other
: error: bash -c 'echo trouble reaching $1 >&2 ; test $1 = main || exit 4 ; echo ok' -- other exited with 4

Ask quietly and it fails just the same.

#+NAME: run-quiet-failing-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk check-cluster --quiet other 2>&1
#+END_SRC

#+RESULTS[e293314ba6a24120bf65be8a6f5b5870a88963d0]: run-quiet-failing-demo
: error: bash -c 'echo trouble reaching $1 >&2 ; test $1 = main || exit 4 ; echo ok' -- other exited with 4, saying:
: error: trouble reaching other

Of course, you can use ~--timeout~ as well.

#+NAME: create_waiting_command
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk command create --extension cluster-demo python watch-cluster --description "Wait for the cluster to answer" --body '
import subprocess

from clk.lib import check_output

@command()
@option("--timeout", type=int, default=30, help="How long to give the cluster to answer")
def watch_cluster(timeout):
    """Wait for the cluster to answer, but not for ever."""
    try:
        print(check_output(["bash", "-c", "sleep 600"], timeout=timeout))
    except subprocess.TimeoutExpired:
        print("giving up, the cluster is not answering")
'
#+END_SRC

#+NAME: run-waiting-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk watch-cluster --timeout 1 2>&1
#+END_SRC

#+RESULTS[df3bc68deb8f3fa3405dea99add46836975ce036]: run-waiting-demo
: error: bash -c 'sleep 600' did not finish in 1s
: giving up, the cluster is not answering

#+NAME: cleanup-cluster-demo
#+BEGIN_SRC bash :results none :exports none :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove cluster-demo
#+END_SRC

* extension names with special characters
  :PROPERTIES:
  :CREATED:  [2026-02-23 08:00]
  :CUSTOM_ID: 1a2b3c4d-5678-90ab-cdef-abcdef012345
  :END:

Sometimes, extension names come from hostnames. For instance, you may want a
per-machine extension whose name is the machine's hostname. Hostnames can contain
dots, at signs, brackets or other characters that are unusual in simple
identifiers. CLK supports this.

#+NAME: create_hostname_extension
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension create "my-host.[example].com"
#+END_SRC

#+NAME: hostname-extension-visible
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension | grep "my-host.\[example\].com"
#+END_SRC

#+RESULTS[7401030ad5104a118c72e41b09d3d841269ea942]: hostname-extension-visible
: my-host.[example].com  Unset            global

Note that clk will always enable the extension matching your hostname, even if
you explicitly disable it in a project. This is practical to put personal
preference in shared project without disturbing the colleagues.

* an extension that outgrew the project
  :PROPERTIES:
  :CUSTOM_ID: an-extension-that-outgrew-the-project
  :END:

Extensions are cheap too, so one often starts inside a project, under whatever
name came to mind.

#+NAME: create-kube
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
mkdir -p tidyproject/.clk
cd tidyproject
clk extension create --local kube
clk command create --extension kube bash run-cluster --description "Run the cluster" --body 'echo "starting the cluster"'
#+END_SRC

#+NAME: kube-is-local
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension show kube
#+END_SRC

#+RESULTS[13cf4fe0728d1c8ab43f682f56f4852a5f250af8]: kube-is-local
: extension    configuration    installation
: -----------  ---------------  --------------
: kube         Unset            local

~clk extension rename~ gives it the name you would have chosen with more time.

#+NAME: rename-kube
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension rename kube kubernetes
clk extension show kubernetes
#+END_SRC

#+RESULTS[079f37cf724bbb9aa0726c3b0cd97b1bdf9e565e]: rename-kube
: extension    configuration    installation
: -----------  ---------------  --------------
: kubernetes   Unset            local

And ~clk extension move~ carries it out of the project, so that it answers
everywhere.

#+NAME: move-kube
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension move kubernetes global
clk extension show kubernetes
#+END_SRC

#+RESULTS[1c67527a4e0a3248d58d4b27a012ad5422382acc]: move-kube
: extension    configuration    installation
: -----------  ---------------  --------------
: kubernetes   Unset            global

#+NAME: leave-tidyproject
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
cd ..
clk run-cluster
#+END_SRC

#+RESULTS[f14b0c3d91d39ba82c3bd5c4aefed193aba7b677]: leave-tidyproject
: starting the cluster

#+NAME: all
#+BEGIN_SRC bash :results none :exports none :tangle ../../tests/use_cases/creating_extensions.sh :noweb yes :shebang "#!/usr/bin/env bash"
  set -eu
<<init>>

<<create_extension>>

<<create_k8s>>

check-result(try-it)

check-result(disable)

check-result(enable-for-one-run)

check-result(enable)

check-result(disable-for-one-run)

<<create_credentials_project>>

<<create_local_credentials>>

check-result(run-flow-in-project)

<<leave_credentials_project>>

check-result(find-it)

<<publish-k8s>>

check-result(lose-k8s)

<<install-k8s>>

check-result(k8s-is-back)

<<another-k8s>>

check-result(refuse-another-k8s)

<<colleague-adds>>

check-result(no-stop-cluster)

<<update-k8s>>

check-result(stop-cluster)

check-result(install-extension)

check-result(describe-hello)

check-result(remove-extension)

check-result(install-extension-github)

check-result(install-extension-name)

<<create_tempdir_extension>>

<<create_tempdir_command>>

check-result(run-tempdir-demo)

<<create_tempfile_command>>

check-result(run-tempfile-demo)

<<cleanup-tempdir-demo>>

<<create_failing_extension>>

<<create_failing_command>>

check-result(run-complaining-demo)

check-result(run-quiet-demo)

check-result(run-failing-demo)

check-result(run-quiet-failing-demo)

<<create_waiting_command>>

check-result(run-waiting-demo)

<<cleanup-cluster-demo>>

<<create_hostname_extension>>

check-result(hostname-extension-visible)

clk extension remove "my-host.[example].com"

<<create-kube>>

check-result(kube-is-local)

check-result(rename-kube)

check-result(move-kube)

check-result(leave-tidyproject)
#+END_SRC
