:PROPERTIES:
:ID:       f47428c2-56ea-4d91-97d9-4f2ff63ef052
:END:
#+language: en
#+options: toc:t
#+EXPORT_FILE_NAME: ./creating_extensions.md

#+CALL: ../../lp.org:check-result()

#+name: init
#+BEGIN_SRC bash :results none :exports none :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
  . ./sandboxing.sh
#+END_SRC
Extensions are folders that contain clk configurations and commands. You can create and share those with your colleagues.

For instance, let's suppose you need to bootstrap a development environment to
work with k8s, you would need to create commands to:
- install the needed binaries dependencies,
- run the cluster,
- start some controllers of your choice,
- run the development environment that would update the cluster automatically.

* creating our own extension
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:36]
  :ID:       ce7e4602-baad-4ce6-8b44-33d5480a264b
  :CUSTOM_ID: 578ef2c9-a4d4-448a-9d56-be4afe4ac64a
  :END:

The real life extension can be found in [[https://github.com/clk-project/clk_extension_k8s][here]]. In this document, we will mock its
behavior. There should be something like.

#+NAME: k8s
#+BEGIN_SRC python :results none :exports code
@k8s.command()
def install_dependencies():
    """Install the required binary dependencies for k8s development."""
    print("installing dependencies")

@k8s.command(flowdepends=["k8s.install-dependencies"])
def run_cluster():
    """Start the Kubernetes cluster."""
    print("starting k8s cluster")

@k8s.command(flowdepends=["k8s.run-cluster"])
def start_controllers():
    """Start the necessary controllers for the k8s environment."""
    print("starting controllers")

@k8s.command(flowdepends=["k8s.start-controllers"])
def run_dev_env():
    """Run the development environment with automatic cluster updates."""
    print("running development environment")

#+END_SRC

To share them, you would first need to create the extension named k8s.

#+NAME: create_extension
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension create k8s
#+END_SRC

Them, create the k8s command inside the extension.

#+NAME: create_k8s
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052 :noweb yes
clk command create --extension k8s python k8s --group --description "Deal with k8s stuff" --body '
<<k8s>>
'
#+END_SRC

Try it with

#+NAME: try-it
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk k8s run-dev-env --flow
#+END_SRC

#+RESULTS[dca9e20533f99e1b8bd8894585c93baaa2938506]: try-it
: installing dependencies
: starting k8s cluster
: starting controllers
: running development environment

* enable/disable it
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:36]
  :CUSTOM_ID: 72f61beb-cd79-4fdd-86a2-2c56ef08292c
  :END:

Note that once it is there, the extension is automatically enabled.

Now, if you decide that you don't want to be bothered with that extension anymore, you can disable it.

#+NAME: disable
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension disable k8s
clk k8s run-dev-env --flow
#+END_SRC

#+RESULTS[caa531b03ee6b31d35eed3a0dc93b254d4545bbc]: disable
: warning: Failed to get the command k8s: Command k8s not found
: Usage: clk [OPTIONS] COMMAND [ARGS]...
: error: No such command 'k8s'.

You can enable it again with.

#+NAME: enable
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension enable k8s
clk k8s run-dev-env --flow
#+END_SRC

#+RESULTS[4e819e7f946a0c3fb4c8bc4ba83d438fa796c0c5]: enable
: installing dependencies
: starting k8s cluster
: starting controllers
: running development environment

* publish it
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:37]
  :CUSTOM_ID: 21d2895b-db01-4a09-b2a2-18e34e2830b6
  :END:

In case you lost that extension folder and want to find it again, simply run.

#+NAME: find-it
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension where-is global/k8s
#+END_SRC

#+RESULTS[5ee58c93da49807a24b9fab6e6bb97026578103e]: find-it
: ./clk-root/extensions/k8s

You can git init that code and push it to some remote repository. Your
colleagues then can get it with ~clk extension install yourextensionurl~.

* get an extension
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:37]
  :ID:       2907a837-a58d-479b-8d19-7cba1c9a408f
  :CUSTOM_ID: b7bcef53-dd68-4660-9c5c-d9aa029d1a72
  :END:

Let's try to install another extension for the sake of learning. Let's try to
install the one available in https://github.com/clk-project/clk_extension_hello
. It does nothing useful. It simply says hello in a funny way.

There are three ways to provide the url to the extension:
1. use the full url to the git remote,
2. if it is hosted in github, and its repository name is something like
   ~clk_extension_NAME~, then you can simply pass ~<GITHUB_OWNER>/<NAME>~. This
   will be automatically changed into ~https://github.com/<GITHUB_OWNER>/clk_extension_<NAME>~.
3. if it is an official extension provided by clk (meaning hosted at https://github.com/orgs/clk-project/repositories with the
   prefix ~clk_extension_~), then the name will suffice.


Let's try the three methods.

#+NAME: install-extension
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension install https://github.com/clk-project/clk_extension_hello > /dev/null 2>&1
clk hello
#+END_SRC

#+RESULTS[ddc8b5f07fbf3c07198b62e1c6dd77537bdce685]: install-extension
#+begin_example
_____
| hello |
  =====
       \
        \
         \
          \
                                / \\  //\\
                 |\\___/|      /   \\//  \\\\
                 /0  0  \\__  /    //  | \\ \\
                /     /  \\/_/    //   |  \\  \\
                \@_^_\@'/   \\/_   //    |   \\   \\
                //_^_/     \\/_ //     |    \\    \\
             ( //) |        \\///      |     \\     \\
           ( / /) _|_ /   )  //       |      \\     _\\
         ( // /) '/,_ _ _/  ( ; -.    |    _ _\\.-~        .-~~~^-.
       (( / / )) ,-{        _      `-.|.-~-.           .~         `.
      (( // / ))  '/\\      /                 ~-. _ .-~      .-~^-.  \\
      (( /// ))      `.   {            }                   /      \\  \\
       (( / ))     .----~-.\\        \\-'                 .~         \\  `. \\^-.
                  ///.----..>        \\             _ -~             `.  ^-`  ^-_
                    ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                       /.-~
#+end_example

Remove the extension with

#+NAME: remove-extension
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove hello
clk hello
#+END_SRC

#+RESULTS[16bb914fcc2d2d14fd1d6f6aa8abf780c09ddedd]: remove-extension
: warning: Failed to get the command hello: Command hello not found
: Usage: clk [OPTIONS] COMMAND [ARGS]...
: error: No such command 'hello'.
: error:
: error: Did you mean one of these?
: error:     help
: error:     log

Because it is hosted on github, this should do as well to install it.

#+NAME: install-extension-github
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension install clk-project/hello > /dev/null 2>&1
clk hello
#+END_SRC

#+RESULTS[49c1c62970af8db344f9ad2e27ecb87082431174]: install-extension-github
#+begin_example
_____
| hello |
  =====
       \
        \
         \
          \
                                / \\  //\\
                 |\\___/|      /   \\//  \\\\
                 /0  0  \\__  /    //  | \\ \\
                /     /  \\/_/    //   |  \\  \\
                \@_^_\@'/   \\/_   //    |   \\   \\
                //_^_/     \\/_ //     |    \\    \\
             ( //) |        \\///      |     \\     \\
           ( / /) _|_ /   )  //       |      \\     _\\
         ( // /) '/,_ _ _/  ( ; -.    |    _ _\\.-~        .-~~~^-.
       (( / / )) ,-{        _      `-.|.-~-.           .~         `.
      (( // / ))  '/\\      /                 ~-. _ .-~      .-~^-.  \\
      (( /// ))      `.   {            }                   /      \\  \\
       (( / ))     .----~-.\\        \\-'                 .~         \\  `. \\^-.
                  ///.----..>        \\             _ -~             `.  ^-`  ^-_
                    ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                       /.-~
#+end_example

And because this is also a clk provided extension, the name is enough.

#+NAME: install-extension-name
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove hello
clk extension install hello > /dev/null 2>&1
clk hello
#+END_SRC

#+RESULTS[57260c733fd9dbb7ef455f4c6a567e0fab79bc82]: install-extension-name
#+begin_example
_____
| hello |
  =====
       \
        \
         \
          \
                                / \\  //\\
                 |\\___/|      /   \\//  \\\\
                 /0  0  \\__  /    //  | \\ \\
                /     /  \\/_/    //   |  \\  \\
                \@_^_\@'/   \\/_   //    |   \\   \\
                //_^_/     \\/_ //     |    \\    \\
             ( //) |        \\///      |     \\     \\
           ( / /) _|_ /   )  //       |      \\     _\\
         ( // /) '/,_ _ _/  ( ; -.    |    _ _\\.-~        .-~~~^-.
       (( / / )) ,-{        _      `-.|.-~-.           .~         `.
      (( // / ))  '/\\      /                 ~-. _ .-~      .-~^-.  \\
      (( /// ))      `.   {            }                   /      \\  \\
       (( / ))     .----~-.\\        \\-'                 .~         \\  `. \\^-.
                  ///.----..>        \\             _ -~             `.  ^-`  ^-_
                    ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
                                                                       /.-~
#+end_example

* using temporary files and directories
  :PROPERTIES:
  :CREATED:  [2025-12-30 17:38]
  :ID:       a1b2c3d4-5678-90ab-cdef-1234567890ab
  :CUSTOM_ID: 795e915b-29f5-4fbc-a8d9-480a094d3e37
  :END:

When writing extensions, you often need to work with temporary files or
directories. clk provides two helpers in ~clk.lib~: ~tempdir~ and
~temporary_file~. They are context managers that automatically clean up after
themselves.

** tempdir
   :PROPERTIES:
   :CUSTOM_ID: 60d4bff1-366d-45cb-b0ce-3bb7468734aa
   :END:

~tempdir()~ creates a temporary directory and returns its path. It is useful
when you need to extract archives and move files around.

Let's mock a typical use case: installing a tool by extracting an archive and
moving the binary to a destination. This pattern is used in the [[https://github.com/clk-project/clk_extension_k8s][k8s extension]]
to install helm, tilt, etc.

#+NAME: create_tempdir_extension
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension create tempdir-demo
#+END_SRC

#+NAME: create_tempdir_command
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk command create --extension tempdir-demo python tempdir-demo --group --description "Demonstrate tempdir usage" --body '
from pathlib import Path
from clk.lib import tempdir, makedirs, move

@tempdir_demo.command()
def install_mock_tool():
    """Mock installing a tool by extracting an archive to a temp dir."""
    install_dir = Path(".")
    with tempdir() as d:
        # Simulate extracting an archive (in real code: extract(url, d))
        extracted_dir = Path(d) / "tool-1.0.0"
        makedirs(extracted_dir)
        tool_binary = extracted_dir / "tool"
        tool_binary.write_text("#!/bin/sh\necho tool v1.0.0")

        # Move the binary to install location
        dest = install_dir / "mock-tool"
        move(tool_binary, dest)
        print(f"Installed: {dest.read_text()}")
    # temp dir is automatically cleaned up
    # clean up the installed file for the demo
    (install_dir / "mock-tool").unlink()
'
#+END_SRC

#+NAME: run-tempdir-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk tempdir-demo install-mock-tool
#+END_SRC

#+RESULTS[f49599b43da3200cf9e53511db4e2aa74ea4fcc3]: run-tempdir-demo
: Installed: #!/bin/sh
: echo tool v1.0.0

** temporary_file
   :PROPERTIES:
   :CUSTOM_ID: d18237dd-7e05-4225-b9de-bf63f09b6d99
   :END:

~temporary_file()~ creates a temporary file. You can optionally pass ~content~
to write initial content. The file is automatically removed when leaving the
context.

This is useful when you need to pass configuration to a command that reads from
a file. The [[https://github.com/clk-project/clk_extension_k8s][k8s extension]] uses this pattern to pass YAML configuration to
kubectl.

#+NAME: create_tempfile_command
#+BEGIN_SRC bash :results none :exports code :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk command create --extension tempdir-demo python apply-mock-config --description "Demonstrate temporary_file usage" --body '
from clk.lib import temporary_file, check_output

@command()
def apply_mock_config():
    """Mock applying a k8s config using a temporary file."""
    config = """apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  key: value
"""
    with temporary_file(content=config) as f:
        # In real code: call(["kubectl", "apply", "-f", f.name])
        # Here we just cat the file to show it works
        result = check_output(["cat", f.name])
        print("Applied config:")
        print(result.strip())
    # temp file is automatically cleaned up
'
#+END_SRC

#+NAME: run-tempfile-demo
#+BEGIN_SRC bash :results verbatim :cache yes :exports both :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk apply-mock-config
#+END_SRC

#+RESULTS[d60f9eef68024528f834ad05173540d29f525def]: run-tempfile-demo
: Applied config:
: apiVersion: v1
: kind: ConfigMap
: metadata:
:   name: my-config
: data:
:   key: value

#+NAME: cleanup-tempdir-demo
#+BEGIN_SRC bash :results none :exports none :session f47428c2-56ea-4d91-97d9-4f2ff63ef052
clk extension remove tempdir-demo
#+END_SRC

#+NAME: all
#+BEGIN_SRC bash :results none :exports none :tangle ../../tests/use_cases/creating_extensions.sh :noweb yes :shebang "#!/bin/bash -eu"
<<init>>

<<create_extension>>

<<create_k8s>>

check-result(try-it)

check-result(disable)

check-result(enable)

check-result(find-it)

check-result(install-extension)

check-result(remove-extension)

check-result(install-extension-github)

check-result(install-extension-name)

<<create_tempdir_extension>>

<<create_tempdir_command>>

check-result(run-tempdir-demo)

<<create_tempfile_command>>

check-result(run-tempfile-demo)

<<cleanup-tempdir-demo>>
#+END_SRC
