#!/bin/bash -eu
# Generate index-fragment.org from #+SUBTITLE: metadata and code block analysis.
# README.org includes this file via #+INCLUDE, so it appears in the exported README.md.
# Called automatically via pre-commit when org files change.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOC_DIR="${SCRIPT_DIR}"
OUTPUT="${DOC_DIR}/index-fragment.org"

CLK_PATTERNS='clk_[a-z_]+|CLK___[A-Z_]+|^[[:space:]]*[AOFNM]:'

{
    cat <<'HEADER'
#+begin_export md
<!-- Auto-generated by generate-index.sh — do not edit manually -->

# Documentation Index

## Use cases by file

| File | Description | Auto-detected keywords |
|------|-------------|----------------------|
HEADER

    for f in "${DOC_DIR}"/*.org; do
        basename="$(basename "$f")"
        case "${basename}" in
            README.org|sandboxing.org|index-fragment.org) continue ;;
        esac

        export_name="$(grep -m1 '^#+EXPORT_FILE_NAME:' "$f" | sed 's|.*\./||')" || true
        if test -z "${export_name}"; then
            continue
        fi

        subtitle="$(grep -m1 '^#+SUBTITLE:' "$f" | sed 's|^#+SUBTITLE: *||')" || true

        keywords="$(sed -n '/^#+BEGIN_SRC/,/^#+END_SRC/p' "$f" \
            | grep -oE "${CLK_PATTERNS}" \
            | tr ' ' '\n' \
            | sed 's/^[[:space:]]*//' \
            | grep -v '^$' \
            | sort -u \
            | paste -sd,)" || true

        echo "| [${export_name}](${export_name}) | ${subtitle} | ${keywords} |"
    done

    cat <<'SEPARATOR'

## Keyword index

SEPARATOR

    declare -A keyword_files
    for f in "${DOC_DIR}"/*.org; do
        basename="$(basename "$f")"
        case "${basename}" in
            README.org|sandboxing.org|index-fragment.org) continue ;;
        esac

        export_name="$(grep -m1 '^#+EXPORT_FILE_NAME:' "$f" | sed 's|.*\./||')" || true
        if test -z "${export_name}"; then
            continue
        fi

        for kw in $(sed -n '/^#+BEGIN_SRC/,/^#+END_SRC/p' "$f" \
            | grep -oE "${CLK_PATTERNS}" \
            | tr ' ' '\n' \
            | sed 's/^[[:space:]]*//' \
            | grep -v '^$' \
            | sort -u); do
            if test -n "${keyword_files[$kw]+x}"; then
                keyword_files[$kw]="${keyword_files[$kw]}, [${export_name}](${export_name})"
            else
                keyword_files[$kw]="[${export_name}](${export_name})"
            fi
        done
    done

    for kw in $(echo "${!keyword_files[@]}" | tr ' ' '\n' | sort); do
        echo "- \`${kw}\` : ${keyword_files[$kw]}"
    done

    echo '#+end_export'

} > "${OUTPUT}"
