#!/usr/bin/env bash
  set -eu
# Generate index-fragment.org from #+SUBTITLE: metadata and code block analysis.
# README.org includes this file via #+INCLUDE, so it appears in the exported README.md.
# Called automatically via pre-commit when org files change.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOC_DIR="${SCRIPT_DIR}"
OUTPUT="${DOC_DIR}/index-fragment.org"

# every command has them, so they point nowhere in particular
CLK_BOILERPLATE='^(clk_help_handler|clk_usage|clk\.decorators\.(argument|command|flag|group|option)|clk\.config\.config|clk\.log\.get_logger)$'

# the code the reader sees: the shown blocks, and the hidden ones they include
shown_code () {
    awk '
        /^[[:space:]]*#\+(NAME|name):/ { name = $2; next }
        /^[[:space:]]*#\+(BEGIN_SRC|begin_src)/ {
            n++; inside = 1
            names[n] = name; name = ""
            shown[n] = ($0 !~ /:exports none/)
            next
        }
        /^[[:space:]]*#\+(END_SRC|end_src)/ { inside = 0; next }
        inside { code[n] = code[n] $0 "\n" }
        END {
            do {
                changed = 0
                for (i = 1; i <= n; i++) {
                    if (!shown[i]) continue
                    for (j = 1; j <= n; j++) {
                        if (!shown[j] && names[j] != "" && index(code[i], "<<" names[j] ">>")) {
                            shown[j] = 1; changed = 1
                        }
                    }
                }
            } while (changed)
            for (i = 1; i <= n; i++) if (shown[i]) printf "%s", code[i]
        }
    ' "$1"
}

# the bash helpers, the variables clk reads and what the python code takes from clk
keywords_of () {
    local code
    code="$(shown_code "$1")"
    {
        grep -oE 'clk_[a-z_]+|CLK_[A-Z][A-Z_]*|expose_class' <<< "${code}"
        awk '
            match($0, /^[[:space:]]*from clk[.a-z_]* import/) {
                module = $0
                sub(/^[[:space:]]*from /, "", module)
                sub(/ import.*/, "", module)
                names = $0
                sub(/.* import[[:space:]]*/, "", names)
                paren = (names ~ /^\(/ && names !~ /\)/)
                print module " " names
                next
            }
            paren {
                print module " " $0
                if ($0 ~ /\)/) paren = 0
            }
        ' <<< "${code}" \
            | sed 's/#.*//; s/[()]//g' \
            | while read -r module names; do
                  tr ',' '\n' <<< "${names}" | sed 's/[[:space:]]//g' | grep -v '^$' \
                      | sed "s/^/${module}./"
              done
    } | grep -vE "${CLK_BOILERPLATE}" | sort -u
}

{
    cat <<'HEADER'
#+begin_export md
<!-- Auto-generated by generate-index.sh — do not edit manually -->

# Documentation Index

## Use cases by file

| File | Description | Auto-detected keywords |
|------|-------------|----------------------|
HEADER

    for f in "${DOC_DIR}"/*.org; do
        basename="$(basename "$f")"
        case "${basename}" in
            README.org|sandboxing.org|index-fragment.org) continue ;;
        esac

        export_name="$(grep -m1 '^#+EXPORT_FILE_NAME:' "$f" | sed 's|.*\./||')" || true
        if test -z "${export_name}"; then
            continue
        fi

        subtitle="$(grep -m1 '^#+SUBTITLE:' "$f" | sed 's|^#+SUBTITLE: *||')" || true

        keywords="$(keywords_of "$f" | paste -sd,)" || true

        echo "| [${export_name}](${export_name}) | ${subtitle} | ${keywords} |"
    done

    cat <<'SEPARATOR'

## Keyword index

SEPARATOR

    declare -A keyword_files
    for f in "${DOC_DIR}"/*.org; do
        basename="$(basename "$f")"
        case "${basename}" in
            README.org|sandboxing.org|index-fragment.org) continue ;;
        esac

        export_name="$(grep -m1 '^#+EXPORT_FILE_NAME:' "$f" | sed 's|.*\./||')" || true
        if test -z "${export_name}"; then
            continue
        fi

        for kw in $(keywords_of "$f"); do
            if test -n "${keyword_files[$kw]+x}"; then
                keyword_files[$kw]="${keyword_files[$kw]}, [${export_name}](${export_name})"
            else
                keyword_files[$kw]="[${export_name}](${export_name})"
            fi
        done
    done

    for kw in $(echo "${!keyword_files[@]}" | tr ' ' '\n' | sort); do
        echo "- \`${kw}\` : ${keyword_files[$kw]}"
    done

    echo '#+end_export'

} > "${OUTPUT}"
