:PROPERTIES:
:ID:       0ecfb0d2-433b-4b34-8a4a-529603d8e669
:END:
#+language: en
#+EXPORT_FILE_NAME: ./lib.md
#+SUBTITLE: Reference for clk.lib Python helpers (download, echo_json, etc.)

#+BEGIN_SRC elisp :exports none :results none
  (org-gfm-export-to-markdown)
#+END_SRC

There are several stuff that you will always need to have at hand when
developing command line commands.

* Getting files
  :PROPERTIES:
  :CUSTOM_ID: 780a9f7a-801f-4f4b-83ef-7bfffdf71372
  :END:

Often, files are available as zip of tar archives in web servers. A function
that, given a url, would download and extract its content would be very useful.

#+name:extract
#+BEGIN_SRC python :results verbatim :exports both :session
    from pathlib import Path

    from clk.lib import extract

    f = Path("readme")

    assert not f.exists()
    extract("https://github.com/clk-project/clk/raw/main/tests/zipfile.zip")
    assert f.exists()
    assert f.read_text() == "hello from some zip file\n"
#+END_SRC

If you wish to simply download the file, just call download. See
[[file:fetching_and_displaying_json_data.org][fetching and displaying JSON data]] for a complete example of using ~download~.

When you know what the file should be, say so with ~sha256~.

#+name:download
#+BEGIN_SRC python :results verbatim :exports both :session
    from clk.lib import download

    archive = download(
        "https://github.com/clk-project/clk/raw/main/tests/zipfile.zip",
        sha256="702bb46372dfad9632c8dc3d8b5bbe945f9efd2f5575723bf66a0128486b7fb5",
    )
    assert archive.exists()
#+END_SRC

Should the server hand you anything else, nothing is written at all.

#+name:download-corrupted
#+BEGIN_SRC python :results verbatim :exports both :session
    import click
    import pytest

    archive.unlink()
    with pytest.raises(click.ClickException):
        download(
            "https://github.com/clk-project/clk/raw/main/tests/zipfile.zip",
            sha256="0" * 64,
        )
    assert not archive.exists()
#+END_SRC

* Running programs
  :PROPERTIES:
  :CUSTOM_ID: 4416a8cc-4d3a-4162-a590-a67be3f9033a
  :END:

~check_output~ hands you what the program wrote. When it fails, it tells what
the program said on its error output before raising, so you don't have to.

#+name:check-output-failing
#+BEGIN_SRC python :results verbatim :exports both :session
    import subprocess

    import pytest

    from clk.lib import check_output

    with pytest.raises(subprocess.CalledProcessError) as failure:
        check_output(["bash", "-c", "echo 'model.cpp:42: chaos is not defined' >&2 ; exit 2"])

    assert failure.value.returncode == 2
    assert failure.value.stderr == "model.cpp:42: chaos is not defined\n"
#+END_SRC

A program that wins while complaining keeps its complaint, which goes to your
error output, and you get its answer.

#+name:check-output-noisy
#+BEGIN_SRC python :results verbatim :exports both :session
    from clk.lib import check_output

    assert check_output(
        ["bash", "-c", "echo 'linking takes a while' >&2 ; echo ./build/simulator"]
    ) == "./build/simulator\n"
#+END_SRC

* Tangling                                                         :noexport:
  :PROPERTIES:
  :CUSTOM_ID: 4deb6976-5708-4527-8ed8-c2ab9de8cc38
  :END:
#+BEGIN_SRC python :tangle ../../tests/use_cases/../test_lib2.py :exports none  :noweb yes :shebang "#!/usr/bin/env python3"

# Automatically generated, don't edit


def test_extract():
    <<extract>>


def test_download():
    <<download>>
    <<download-corrupted>>


def test_check_output_failing():
    <<check-output-failing>>


def test_check_output_noisy():
    <<check-output-noisy>>



#+END_SRC
