:PROPERTIES:
:ID:       b115ee6f-3575-46e0-a64c-880cfa22d4e3
:END:
#+language: en
#+EXPORT_FILE_NAME: ./python_command.md
#+SUBTITLE: Creating Python commands with clk command create python, click decorators

#+CALL: ../../lp.org:check-result()

#+name: init
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3
  . ./sandboxing.sh
#+END_SRC

To create a python command, you can simply call the following command.

#+name: create
#+BEGIN_SRC bash :results none :exports code :session b115ee6f-3575-46e0-a64c-880cfa22d4e3
clk command create python mycommand
#+END_SRC

Your editor will be used to first edit the command. This command will already
contain some code to get you started.

Note that you can always get the help of any command using ~--help~. So don't
hesitate to try.

#+NAME: help-create
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk command create python --help
#+END_SRC

#+RESULTS[79bb39f6967899be6a29ac0b6c90699bf3a824a2]: help-create
#+begin_example
Usage: clk command create python [OPTIONS] NAME

  Create a bash custom command

  This is a built-in command.

Positional arguments:
  NAME  The name of the new command

Options:
  --open / --no-open   Also open the file after its creation  [default: open]
  --force              Overwrite a file if it already exists
  --group / --command  Bootstrap a command or a group of commands  [default: command]
  --with-data          Create a directory module instead of a single file. So that you can ship data with it
  --body TEXT          The initial body to put  [default: ""]
  --description TEXT   The initial description to put  [default: Description]
  --from-file TEXT     Copy this file instead of using the template
  --help-all           Show the full help message, automatic options included.
  --help               Show this message and exit.
#+end_example

Let's look at the file that was created.

#+NAME: show_it
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
cat $(clk command which mycommand)
#+END_SRC

#+RESULTS[f1f70dbaf02e9ced27bf20557c8ec71e3d29f6a5]: show_it
#+begin_example
#!/usr/bin/env python3
# -*- coding:utf-8 -*-

from pathlib import Path

import click

from clk.decorators import (
    argument,
    flag,
    option,
    command,
    use_settings,
    table_format,
    table_fields,
)
from clk.lib import (
    TablePrinter,
    call,
)
from clk.config import config
from clk.log import get_logger
from clk.types import DynamicChoice


LOGGER = get_logger(__name__)


@command()
def mycommand():
    "Description"
#+end_example

The ~@command()~ decorator is provided by clk. It is a thin wrapper around the
click ~@command()~ decorator that adds some features like automatic option
handling.

Let's run this command.

#+NAME: try
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand
#+END_SRC

#+RESULTS[c79c1298c6898b13962d7526bd02cf22c63d1d54]: try
: warning: The command 'mycommand' has no documentation

If you keep the word ~Description~ in the help message, clk will warn you that
you should replace it with something more interesting.

Let's write something in here.

#+name: set_description
#+BEGIN_SRC bash :results none :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3
sed -i 's/"Description"/"Command that says something"/g' "$(clk command which mycommand)"
#+END_SRC

#+NAME: help
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand --help | head -10
#+END_SRC

#+RESULTS[fe88f92e0d201f6a77507ea5266987c47bb4b62d]: help
#+begin_example
Usage: clk mycommand [OPTIONS]

  Command that says something

  Edit this custom command by running `clk command edit mycommand`
  Or edit ./clk-root/python/mycommand.py directly.

Options:
  --help-all  Show the full help message, automatic options included.
  --help      Show this message and exit.
#+end_example

Let's make this command say something.

#+name: say_something_code
#+BEGIN_SRC python :exports code
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from clk.decorators import command


@command()
def mycommand():
    "Command that says something"
    print("something")
#+END_SRC

#+name: say_something
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :noweb yes
cat<<'EOF' > "$(clk command which mycommand)"
<<say_something_code>>
EOF
#+END_SRC

#+NAME: use_it
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand
#+END_SRC

#+RESULTS[c79c1298c6898b13962d7526bd02cf22c63d1d54]: use_it
: something

* adding options and arguments
  :PROPERTIES:
  :CUSTOM_ID: adding-options-and-arguments
  :END:

You can add options and arguments to your command using click decorators. clk
provides wrappers for them in ~clk.decorators~.

#+name: required_arg_code
#+BEGIN_SRC python :exports code
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from clk.decorators import command, argument


@command()
@argument("name", help="Your name")
def mycommand(name):
    "A command that requires a name"
    print(f"Hello, {name}!")
#+END_SRC

#+name: required_arg_write
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :noweb yes
cat<<'EOF' > "$(clk command which mycommand)"
<<required_arg_code>>
EOF
#+END_SRC

An argument is required by default. Calling the command without it produces an
error.

#+NAME: required_arg_error
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand 2>&1
#+END_SRC

#+RESULTS[76711de6442bd1f02490f922930c8dac3becf124]: required_arg_error
: Usage: clk mycommand [OPTIONS] NAME
: error: Missing argument 'NAME'.

Providing the argument works as expected.

#+NAME: required_arg_ok
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand World
#+END_SRC

#+RESULTS[c5e433d65600c3f0588b7d99d481483b1efa09dd]: required_arg_ok
: Hello, World!

* adding a default value
  :PROPERTIES:
  :CUSTOM_ID: adding-a-default-value
  :END:

You can make an argument optional by providing a ~default~ value. You can also
add options and flags.

#+name: with_options_code
#+BEGIN_SRC python :exports code
  #!/usr/bin/env python3
  # -*- coding: utf-8 -*-

  from clk.decorators import command, option, argument


  @command()
  @option("--name", default="world", help="Name to greet")
  @option("--use-name", default="world", help="Name to greet", deprecated="since forever")
  @argument("greeting", default="Hello")
  def mycommand(name, greeting, use_name):
      "A greeting command"
      name = name or use_name
      print(f"{greeting}, {name}!")
#+END_SRC

#+name: with_options
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :noweb yes
cat<<'EOF' > "$(clk command which mycommand)"
<<with_options_code>>
EOF
#+END_SRC

#+NAME: use_with_options
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand
#+END_SRC

#+RESULTS[c79c1298c6898b13962d7526bd02cf22c63d1d54]: use_with_options
: warning: The parameter 'greeting' in the command 'mycommand' has no documentation
: Hello, world!

#+NAME: use_with_options2
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand --name clk Goodbye
#+END_SRC

#+RESULTS[af16c7dfc8e6d93fc671a29deb20e345466a5c3a]: use_with_options2
: warning: The parameter 'greeting' in the command 'mycommand' has no documentation
: Goodbye, clk!

#+NAME: use_with_deprecated_options
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand --use-name clk Goodbye
#+END_SRC

#+RESULTS[fef9f1cd56d15dd24a3b5714c4f61efa70102b0c]: use_with_deprecated_options
: DeprecationWarning: The option 'use_name' is deprecated. since forever
: warning: The parameter 'greeting' in the command 'mycommand' has no documentation
: Goodbye, world!

That warning about ~greeting~ shows in the help as well.

#+NAME: help_without_doc
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand --help 2>/dev/null
#+END_SRC

#+RESULTS[]: help_without_doc
#+begin_example
Usage: clk mycommand [OPTIONS] [GREETING]

  A greeting command

  Edit this custom command by running `clk command edit mycommand`
  Or edit ./clk-root/python/mycommand.py directly.

Options:
  --name TEXT      Name to greet  [default: world]
  --use-name TEXT  Name to greet (DEPRECATED: since forever)  [default: world]
  --help-all       Show the full help message, automatic options included.
  --help           Show this message and exit.
#+end_example

Give it a help of its own.

#+NAME: documented_arg_code
#+BEGIN_SRC python :exports code
@argument("greeting", default="Hello", help="What to say")
#+END_SRC

#+NAME: document_arg
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3
sed -i 's|default="Hello")|default="Hello", help="What to say")|' "$(clk command which mycommand)"
#+END_SRC

#+NAME: help_with_doc
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mycommand Goodbye
clk mycommand --help | grep -A1 "Positional arguments:"
#+END_SRC

#+RESULTS[]: help_with_doc
: Goodbye, world!
: Positional arguments:
:   [GREETING]  What to say  [default: Hello]

* possible mistake: forgetting the decorator
  :PROPERTIES:
  :CUSTOM_ID: forgetting-the-decorator
  :END:

When creating python custom commands manually, you need to use the ~@command()~
or ~@group()~ decorator from clk. If you forget to do so, clk will provide a
helpful error message. Note however that if you use ~clk command create~, you
should not worry about that.

Let's create a python file that defines a function but forgets to decorate it.

#+NAME: bad-command-code
#+BEGIN_SRC python :exports code
def pyenv():
    """My environment command"""
    print("hello")
#+END_SRC

#+NAME: create-bad-command
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :noweb yes
cat <<'EOF' > "${CLKCONFIGDIR}/python/pyenv.py"
<<bad-command-code>>
EOF
#+END_SRC

Now try reaching it.

#+NAME: ask-for-completion-bad-command
#+BEGIN_SRC bash :results none :exports code
clk py<TAB>
#+END_SRC

#+NAME: try-completion-bad-command
#+BEGIN_SRC bash :results verbatim :exports results :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk completion try --last clk py
#+END_SRC

#+RESULTS[476b7858565aa8754ee455b037c20f1ed00f1762]: try-completion-bad-command
: python

It does not come up. That is the hint that something is wrong with it, and
running it says what.

#+NAME: try-bad-command
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk pyenv 2>&1|sed "s|$(pwd)|.|"
#+END_SRC

#+RESULTS[d3af7307b4a90513093c8fec7eb41ccf188e9537]: try-bad-command
: error: Found the command pyenv in the resolver customcommand but could not load it.
: warning: Failed to get the command pyenv: The file ./clk-root/python/pyenv.py must contain a click command or group named pyenv, but found a function instead. Did you forget the @command or @group decorator?
: error: clk.pyenv could not be loaded. Re run with clk --develop to see the stacktrace or clk --debug-on-command-load-error to debug the load error

Let's take a look at the stack trace with ~--develop~.

#+NAME: try-bad-command-develop
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk --develop pyenv 2>&1 | grep -o 'raise BadCustomCommandError('
#+END_SRC

#+RESULTS[7e88fa48af92c11daab9f1cb04ae89d613d0d31f]: try-bad-command-develop
: raise BadCustomCommandError(

Of course, you won't be able to complete on that command.

#+NAME: ask-for-completion-bad-command-options
#+BEGIN_SRC bash :results none :exports code
clk pyenv --<TAB>
#+END_SRC

#+NAME: try-completion-bad-command-options
#+BEGIN_SRC bash :results verbatim :exports results :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk completion try --last clk pyenv --
#+END_SRC

#+RESULTS[1bb9117ee25cce8c33abcf2739080c6cc24f6c9e]: try-completion-bad-command-options

To fix this, simply add the ~@command()~ decorator from clk.

#+NAME: fix-command-code
#+BEGIN_SRC python :exports code
from clk.decorators import command

@command()
def pyenv():
    """My environment command"""
    print("hello")
#+END_SRC

#+NAME: fix-command
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :noweb yes
cat <<'EOF' > "${CLKCONFIGDIR}/python/pyenv.py"
<<fix-command-code>>
EOF
#+END_SRC

Now the command works as expected.

#+NAME: try-fixed-command
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk pyenv
#+END_SRC

#+RESULTS[053668cb456edd0a9d8737397024c568fa0f313e]: try-fixed-command
: hello

* possible mistake: using periods in python command names
  :PROPERTIES:
  :CUSTOM_ID: periods-in-python-command-names
  :ID:       d9ba5b67-bc5d-4a07-b1c9-cac12a0414ee
  :END:

Unlike bash commands, where the period character can be used to put a command
inside a group (e.g. ~somegroup.somecommand~), python command names cannot
contain periods. The name is used as a Python identifier, so periods would
produce invalid code.

#+NAME: create-periods
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk command create python something.with.periods 2>&1
#+END_SRC

#+RESULTS[8538e1d58ed9f1109a1f7a7b65c661502a419577]: create-periods
: Usage: clk command create python [OPTIONS] NAME
: error: 'something.with.periods' is not a valid Python command name (it contains periods). Python command names must be valid Python identifiers. If you want to create a command inside a group, first create the group with 'clk command create python --group mygroup', then add the command inside it.

To create a command inside a group, first create the group as a python command
with ~--group~, then edit it to add the child command inside.

#+NAME: create-mygroup
#+BEGIN_SRC bash :results none :exports code :session b115ee6f-3575-46e0-a64c-880cfa22d4e3
clk command create python --group mygroup
#+END_SRC

Then edit the group file to add the child command.

#+NAME: mygroup-with-child-code
#+BEGIN_SRC python :exports code
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from clk.decorators import group, command


@group()
def mygroup():
    "My group of commands"


@mygroup.command()
def child():
    "A command inside mygroup"
    print("hello from mygroup child")
#+END_SRC

#+NAME: mygroup-with-child
#+BEGIN_SRC bash :results none :exports none :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :noweb yes
cat <<'EOF' > "$(clk command which mygroup)"
<<mygroup-with-child-code>>
EOF
#+END_SRC

#+NAME: try-mygroup-child
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk mygroup child
#+END_SRC

#+RESULTS[e243f68a2d1e37992ff663d9518a348041fa2f8c]: try-mygroup-child
: hello from mygroup child

* shipping data along with the command
  :PROPERTIES:
  :CUSTOM_ID: shipping-data-along-with-the-command
  :END:

A command sometimes needs files of its own: a template, a key, a picture. With
~--with-data~, it becomes a folder instead of a single file, and those files live
in it.

#+NAME: greet-code
#+BEGIN_SRC python :results none :exports code
from pathlib import Path

from clk.decorators import command


@command()
def greet():
    """Greet the way this machine greets"""
    print((Path(__file__).parent / "greeting.txt").read_text().strip())
#+END_SRC

#+NAME: create-greet
#+BEGIN_SRC bash :results none :exports code :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :noweb yes
clk command create python greet --with-data --description "Greet someone" --body '
<<greet-code>>
'
#+END_SRC

It is a package now, so the command is its ~__init__.py~.

#+NAME: where-greet
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk command which greet | sed "s|$(pwd)|.|"
#+END_SRC

#+RESULTS[8352199446e5a733e3da87c58ee088be97fcd861]: where-greet
: ./clk-root/python/greet/__init__.py

Put the file it wants next to it.

#+NAME: add-greeting
#+BEGIN_SRC bash :results none :exports code :session b115ee6f-3575-46e0-a64c-880cfa22d4e3
echo "Hello, and welcome aboard" > "$(dirname "$(clk command which greet)")/greeting.txt"
#+END_SRC

#+NAME: try-greet
#+BEGIN_SRC bash :results verbatim :exports both :session b115ee6f-3575-46e0-a64c-880cfa22d4e3 :cache yes
clk greet
#+END_SRC

#+RESULTS[39ff500940a446a3cba6bd99d26b7fa06a37b964]: try-greet
: Hello, and welcome aboard

#+BEGIN_SRC bash :exports none :tangle ../../tests/use_cases/python_command.sh :noweb yes :shebang "#!/usr/bin/env bash"
  set -eu
<<init>>

<<create>>

check-result(help-create)

check-result(show_it)

check-result(try)

<<set_description>>

check-result(help)

<<say_something>>

check-result(use_it)

<<required_arg_write>>

check-result(required_arg_error)

check-result(required_arg_ok)

<<with_options>>

check-result(use_with_options)

check-result(use_with_options2)

check-result(use_with_deprecated_options)

check-result(help_without_doc)

<<document_arg>>

check-result(help_with_doc)

<<create-bad-command>>

check-result(try-completion-bad-command)

check-result(try-bad-command)
check-result(try-bad-command-develop)

check-result(try-completion-bad-command-options)

<<fix-command>>

check-result(try-fixed-command)

check-result(create-periods)

<<create-mygroup>>

<<mygroup-with-child>>

check-result(try-mygroup-child)

<<create-greet>>

check-result(where-greet)

<<add-greeting>>

check-result(try-greet)
#+END_SRC
