;;; Directory Local Variables            -*- no-byte-compile: t -*-
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((konix/agent-shell-tool-blacklist-project . (("^\\./tangle\\.sh" . "./tangle-n-export.sh")
                                                      ("^./doc/use_cases/generate-index.sh$" . "this is done in a pre-commit hook")
                                                      ("^Edit tests/use_cases/" . "Never touch that file. It is tangled from ./doc/use_cases/")
                                                      ("^\\./export\\.sh" . "./tangle-n-export.sh")
                                                      ("^clk python -m pytest" . "use clk test")
                                                      ("@mcp(mcp__konix-coord__coord_sleep)" . "gh run watch")
                                                      ("^ruff check" . "run pre-commit")
                                                      ))
         (konix/agent-shell-tool-whitelist-project . (("^rm -f tests/\\.coverage\\.\\*" . "")
                                                      ("^clk test" . "")
                                                      ("^bash doc/use_cases/generate-index\\.sh" . "")
                                                      ("^\\./org-process\\.sh\\( doc/use_cases/\\)?" . "")
                                                      ("^ruff check clk/" . "")
                                                      ("^pre-commit run" . "")
                                                      ("^earthly \\+export-coverage --use_git=true" . "")
                                                      ))
         (konix/agent-shell-mcp-project-servers . ("konix-emacs-code-review"
                                                   "konix-emacs-workspace"
                                                   ))))
 (org-mode . ((ispell-dictionary . "american")
              (org-id-link-to-org-use-id . nil)
              (org-babel-default-header-args:python . ((:preserve-indentation . t)
                                                       )))))
